baseURL = "http://grahamweldon.com"
languageCode = "en"
title = "Graham Weldon"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "******"

# Google Analytics UA number
googleAnalytics = "UA-289856-5"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 20
  identifier = "posts"
  url = "/post/"

[[menu.main]]
  name = "Works"
  weight = 30
  identifier = "works"
  url = "https://github.com/laozhu"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Graham Weldon"
  avatar = "/img/avatar.jpg"
  seotitle = "Graham Weldon"
  # subtitle = "~ Posts and Research ~"
  description = "Personal blog site of Graham Weldon."
  paginate = 10

  # Choose your social networks
  email = "graham@grahamweldon.com"
  github = "predominant"
  twitter = "predominant"
  linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  youtube = "slavitica"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  # changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
